[versions]
javalin = "6.1.3"
retrofit = "2.11.0"

[libraries]
## Javalin залежності
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }

## Retrofit залежності
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }